- README.md
@LL-Pengfei 
@ZKathrynx 
@tygq13 
@parvathi14 
@kuromono
> [AY1920S1-CS2113-F09-2] Cube

- src/main/java/Duke.java
- src/main/java/command/Command.java
- src/main/java/command/DeadlineCommand.java
- src/main/java/command/DeleteCommand.java
- src/main/java/command/DoneCommand.java
- src/main/java/command/EventCommand.java
- src/main/java/command/ExitCommand.java
- src/main/java/command/HelpCommand.java
- src/main/java/command/ListCommand.java
- src/main/java/command/TodoCommand.java
- src/main/java/exception/DukeException.java
- src/main/java/exception/DukeLoadingException.java
- src/main/java/task/Deadline.java
- src/main/java/task/Event.java
- src/main/java/task/Task.java
- src/main/java/task/TaskList.java
- src/main/java/task/Todo.java
- src/main/java/ui/Message.java
- src/main/java/ui/Ui.java
- src/main/java/util/Parser.java
- src/main/java/util/Storage.java
level 9 version of Duke. I will try to add docs before Wednesday night.
> add all src codes

- src/main/java/Duke.java
- src/main/java/command/Command.java
- src/main/java/command/DeadlineCommand.java
- src/main/java/command/DeleteCommand.java
- src/main/java/command/DoneCommand.java
- src/main/java/command/EventCommand.java
- src/main/java/command/ExitCommand.java
- src/main/java/command/FindCommand.java
- src/main/java/command/HelpCommand.java
- src/main/java/command/ListCommand.java
- src/main/java/command/TodoCommand.java
- src/main/java/exception/DukeException.java
- src/main/java/exception/DukeLoadingException.java
- src/main/java/task/Deadline.java
- src/main/java/task/Event.java
- src/main/java/task/Task.java
- src/main/java/task/TaskList.java
- src/main/java/task/Todo.java
- src/main/java/ui/Message.java
- src/main/java/ui/Ui.java
- src/main/java/util/Parser.java
- src/main/java/util/Storage.java
don't forget to add A-Packages tag
> added docs

- .gitignore
- src/main/java/.idea/misc.xml
- src/main/java/.idea/modules.xml
- src/main/java/.idea/vcs.xml
- src/main/java/Duke.java
- src/main/java/command/FindCommand.java
- src/main/java/command/ReminderCommand.java
- src/main/java/out/production/main/.idea/misc.xml
- src/main/java/out/production/main/.idea/modules.xml
- src/main/java/out/production/main/.idea/vcs.xml
- src/main/java/task/Deadline.java
- src/main/java/task/Event.java
- src/main/java/task/Task.java
- src/main/java/ui/Ui.java
- src/main/java/util/Parser.java
- src/main/java/util/Storage.java
reminder to add tag B-Reminders
> [CS2113T-F09-2]-tygq13-B-Reminders

- src/main/java/.idea/misc.xml
- src/main/java/.idea/modules.xml
- src/main/java/.idea/vcs.xml
- src/main/java/Duke.java
- src/main/java/command/FindCommand.java
- src/main/java/command/FreeTimeCommand.java
- src/main/java/command/ReminderCommand.java
- src/main/java/out/production/main/.idea/misc.xml
- src/main/java/out/production/main/.idea/modules.xml
- src/main/java/out/production/main/.idea/vcs.xml
- src/main/java/task/Deadline.java
- src/main/java/task/Event.java
- src/main/java/task/Task.java
- src/main/java/ui/Ui.java
- src/main/java/util/Parser.java
- src/main/java/util/Storage.java
added feature FreeTime.
remember to add tag B-FindFreeTimes.
> [CS2113T-F09-2]-tygq13-B-FindFreeTimes

- src/main/java/cube/command/DoAfterCommand.java
- src/main/java/cube/command/RecurCommand.java
- src/main/java/cube/task/DoAfter.java
- src/main/java/cube/task/Recur.java
- src/main/java/cube/util/Parser.java
> [F09-2]-<Zkathrynx>-<B-DoAfterTasks>

- src/main/java/cube/command/SnoozeCommand.java
- src/main/java/cube/command/TentSchedCommand.java
- src/main/java/cube/task/TentSched.java
- src/main/java/cube/ui/Ui.java
- src/main/java/cube/util/Parser.java
Tentative Scheduling implemented. Ready to be tagged tentative-scheduling + v1.1
> [CS2113T-F09-2]-LL-Pengfei-B-TentativeScheduling

- src/main/java/.idea/misc.xml
- src/main/java/.idea/modules.xml
- src/main/java/.idea/vcs.xml
- src/main/java/cube/Duke.java
- src/main/java/cube/exception/CubeException.java
- src/main/java/cube/logic/command/AddCommand.java
- src/main/java/cube/logic/command/Command.java
- src/main/java/cube/logic/command/DeleteCommand.java
- src/main/java/cube/logic/command/ExitCommand.java
- src/main/java/cube/logic/command/HelpCommand.java
- src/main/java/cube/logic/command/ListCommand.java
- src/main/java/cube/logic/command/SoldCommand.java
- src/main/java/cube/logic/parser/AddCommandParser.java
- src/main/java/cube/logic/parser/DeleteCommandParser.java
- src/main/java/cube/logic/parser/ListCommandParser.java
- src/main/java/cube/logic/parser/Parser.java
- src/main/java/cube/logic/parser/ParserPrototype.java
- src/main/java/cube/logic/parser/SoldCommandParser.java
- src/main/java/cube/model/food/Food.java
- src/main/java/cube/model/food/FoodList.java
- src/main/java/cube/storage/FoodStorage.java
- src/main/java/cube/storage/RevenueStorage.java
- src/main/java/cube/storage/StorageManager.java
- src/main/java/out/production/main/.idea/misc.xml
- src/main/java/out/production/main/.idea/modules.xml
- src/main/java/out/production/main/.idea/vcs.xml
1. Change logic to Cube.
2. add skeleton for storage, parser, food/foodlist
3. implement Commands (debugging codes undeleted)
programme runnable
> skeleton Cube and implement Command

- src/main/java/cube/ui/Ui.java
pr 20191003 23:45pm
updated ui javadoc to be consistent with cube
> no message

- src/main/java/cube/ui/Ui.java
updated javadoc comment to be consistent with cube
> pr 20191003 23:47pm

- src/main/java/cube/logic/command/AddCommand.java
- src/main/java/cube/logic/command/DeleteCommand.java
- src/main/java/cube/logic/command/ExitCommand.java
- src/main/java/cube/logic/command/HelpCommand.java
- src/main/java/cube/logic/command/ListCommand.java
- src/main/java/cube/logic/command/SoldCommand.java
- src/main/java/cube/logic/parser/AddCommandParser.java
- src/main/java/cube/logic/parser/Parser.java
- src/main/java/cube/model/food/Food.java
- src/main/java/cube/model/food/FoodList.java
- src/main/java/cube/ui/Ui.java
some change in ui class so that command result can be seen.
still cannot store, and some parameter incomplete. will continue working on that
> some changes in ui to show command result

- src/main/java/cube/logic/command/AddCommand.java
- src/main/java/cube/logic/command/DeleteCommand.java
- src/main/java/cube/logic/command/SoldCommand.java
- src/main/java/cube/logic/parser/AddCommandParser.java
- src/main/java/cube/logic/parser/DeleteCommandParser.java
- src/main/java/cube/logic/parser/Parser.java
- src/main/java/cube/logic/parser/ParserUtil.java
- src/main/java/cube/model/food/FoodList.java
Also support delete by name and type.
> Fixed add & delete parser

- src/main/java/cube/command/Command.java
- src/main/java/cube/command/FixedDurationCommand.java
- src/main/java/cube/command/RecurCommand.java
- src/main/java/cube/command/SnoozeCommand.java
- src/main/java/cube/command/TentSchedCommand.java
- src/main/java/cube/command/TimeBoundCommand.java
- src/main/java/cube/exception/DukeLoadingException.java
- src/main/java/cube/util/Storage.java
> fixed storage bug

- src/main/java/cube/logic/command/FindCommand.java
- src/main/java/cube/model/FoodList.java
find and delete by type can work properly now
> fixed null type bug

- src/main/java/cube/logic/command/DeleteCommand.java
- src/main/java/cube/logic/command/GenerateRevenueCommand.java
- src/main/java/cube/logic/parser/GenerateRevenueCommandParser.java
- src/main/java/cube/logic/parser/Parser.java
> generaterevenuecommand implemented (milestone v1.3, issue #51 As a shop owner, I want to see the revenue of certain products or all products.)

- src/main/java/cube/Cube.java
- src/main/java/cube/logic/command/AddCommand.java
- src/main/java/cube/logic/command/Command.java
- src/main/java/cube/logic/command/DeleteCommand.java
- src/main/java/cube/logic/command/ExitCommand.java
- src/main/java/cube/logic/command/FindCommand.java
- src/main/java/cube/logic/command/GenerateRevenueCommand.java
- src/main/java/cube/logic/command/HelpCommand.java
- src/main/java/cube/logic/command/ListCommand.java
- src/main/java/cube/logic/command/ReminderCommand.java
- src/main/java/cube/logic/command/SoldCommand.java
- src/main/java/cube/logic/command/util/CommandResult.java
- src/main/java/cube/logic/command/util/CommandUtil.java
- src/main/java/cube/logic/parser/FindCommandParser.java
- src/main/java/cube/ui/CommandBox.java
- src/main/java/cube/ui/MainWindow.java
- src/main/java/cube/ui/Ui.java
1. move all valid checkers in command to CommandUtil (reduce repeated codes)
2. refactor SoldCommand to follow law of Demeter
3. add javaDoc for commands i wrote
> refactor command valid checkers

- src/main/java/cube/logic/command/SoldCommand.java
- src/main/java/cube/model/sale/Sale.java
- src/main/java/cube/model/sale/SaleUtil.java
- src/main/java/cube/model/sale/SalesHistory.java
this version has fatal bug in storage. Need to repair soon
> complete SoldCommand. Got bug in storage

- build.gradle
- src/main/java/cube/logic/command/ConfigCommand.java
- src/main/java/cube/storage/config/UiConfig.java
- src/main/java/cube/ui/FoodListCard.java
- src/main/java/cube/ui/ListPanel.java
- src/main/java/cube/ui/MainWindow.java
- src/main/resources/view/FoodListCard.fxml
- src/main/resources/view/ListPanel.fxml
- src/main/resources/view/MainWindow.fxml
Added some compiler flags to gradle as well
> Added foodlist to GUI

- src/main/java/cube/logic/command/AddCommand.java
- src/main/java/cube/logic/command/ExitCommand.java
- src/main/java/cube/logic/command/ListCommand.java
- src/main/java/cube/logic/command/util/CommandResult.java
- src/main/java/cube/logic/command/util/CommandUtil.java
- src/main/java/cube/model/food/FoodList.java
- src/main/java/cube/model/food/FoodUtil.java
- src/test/java/cube/logic/command/AddCommandTest.java
- src/test/java/cube/logic/command/ExitCommandTest.java
- src/test/java/cube/logic/command/ListCommandTest.java
- src/test/java/cube/model/food/FoodUtilTest.java
- src/test/java/cube/model/sale/SaleTest.java
- src/test/java/cube/testutil/Assert.java
just added some junit test and some facilitating function for testing
> added some junit test

- src/main/java/cube/logic/command/HelpCommand.java
- src/main/java/cube/logic/parser/ConfigCommandParser.java
- src/main/java/cube/storage/config/UiConfig.java
- src/main/java/cube/ui/MainWindow.java
- src/main/java/cube/ui/OverviewDisplay.java
- src/main/resources/view/MainWindow.fxml
- src/main/resources/view/OverviewDisplay.fxml
> Added Overview to GUI & modify configcommand to allow no args

- src/main/java/cube/logic/parser/PromotionCommandParser.java
assuming inputs to promotion parameters are all correct
> temperary solution to promotion parameters

- src/main/java/cube/logic/command/FindCommand.java
- src/main/java/cube/logic/parser/AddCommandParser.java
- src/main/java/cube/logic/parser/ConfigCommandParser.java
- src/main/java/cube/logic/parser/FindCommandParser.java
- src/main/java/cube/logic/parser/ParserUtil.java
- src/main/java/cube/logic/parser/PromotionCommandParser.java
- src/main/java/cube/logic/parser/ReminderCommandParser.java
- src/main/java/cube/logic/parser/SoldCommandParser.java
- src/main/java/cube/logic/parser/UpdateCommandParser.java
- src/main/java/cube/logic/parser/exception/ParserErrorMessage.java
fixed empty field value bug, foodname trim bug
> Allow finding partial keyword and parser bug fix #2

- src/test/java/cube/logic/command/ListCommandTest.java
- Causing gradle build to fail
> Commented out unused getFoodList in ListCommandTest

- src/main/java/cube/logic/command/BatchCommand.java
- src/main/java/cube/logic/command/exception/CommandErrorMessage.java
- src/main/java/cube/logic/parser/BatchCommandParser.java
- src/main/java/cube/logic/parser/ConfigCommandParser.java
- src/main/java/cube/logic/parser/DeleteCommandParser.java
- src/main/java/cube/logic/parser/FindCommandParser.java
- src/main/java/cube/logic/parser/ProfitCommandParser.java
- src/main/java/cube/logic/parser/RevenueCommandParser.java
- src/main/java/cube/logic/parser/exception/ParserErrorMessage.java
- src/main/java/cube/ui/CommandBox.java
- src/main/java/cube/ui/MainWindow.java
- src/main/java/cube/ui/UiManager.java
> Fix Command Parser Null Bug + BatchCommand generate empty file

- src/main/java/cube/CubeApp.java
- src/main/java/cube/CubeLauncher.java
- src/main/java/cube/logic/command/BatchCommand.java
- src/main/java/cube/logic/command/ConfigCommand.java
- src/main/java/cube/logic/parser/BatchCommandParser.java
- src/main/java/cube/logic/parser/ParserUtil.java
- src/main/java/cube/util/FileUtilCSV.java
- src/test/java/cube/logic/command/BatchCommandTest.java
- src/test/java/cube/logic/command/ConfigCommandTest.java
+ Minor modifications to batch, config command, parserutil, launcher.
> Added JUnit tests for Batch, Config command
